import Head from 'next/head'
import Image from 'next/image'
import Footer from '../comps/footer'
import Navbar from '../comps/navBar'
import styles from '../styles/Home.module.css'
import Link from 'next/dist/client/link'
import styled from "styled-components"
import dynamic from 'next/dynamic'

const BgImage = dynamic(() => import("../comps/BGImage"), {
  ssr: false,
});

const Wrapper = styled.div`
  z-index: 1;
  width: 100%;
  height: 100%;
  /* position: fixed; */
  position: absolute;
 
  
 
`;


export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <>  
      <Wrapper>  

      <Navbar/>   
     

      </Wrapper>  
      <BgImage/> 
      </>

     {/*   <div className="w-full h-full bg-black"> 

</div> */}
     {/*  <div  > 
       <Image
           
           layout="fill"
           objectFit='cover'
           objectPosition="center"
           className="object-center object-cover pointer-events-none"

           alt=""
           src="/fotoA.png"
         
         ></Image>  

      </div>  */}
      

      {/* {fotosFondo.map((foto, i) => (
          <Image
            key={i}
            layout="fill"
            objectFit='cover'
            objectPosition="center"
        

            alt="dsa"
            src="/public/fotpA.png"
          
          ></Image>
        ))} */}
       
          </div>
     /*  <Link href ="/alphabcz">
      <h2 >INDEEEEEX</h2>

      </Link>
      
  */
 
  
  )
}
