import Head from 'next/head'
import Image from 'next/image'
import Footer from '../comps/footer'
import Navbar from '../comps/navBar'
import styles from '../styles/Home.module.css'
import Link from 'next/dist/client/link'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Link href ="/alphabcz">
      <h2 >INDEEEEEX</h2>

      </Link>
 
    </div>
  )
}
